name: Build & deploy artifact
on:
  push:
    branches: [ "main" ]
permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          npm i
          npm run build
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/

      - name: Deploy
        uses: actions/deploy-pages@v3

